
[ClassVersion("1.0.0.0"), FriendlyName("CookbookFile")]
class POSHChef_CookbookFileResource : OMI_BaseResource
{
	[Key, Description("Location of cookbook file")] String Source;
	[Key, Description("Path where the file should be saved")] String Destination;
	[Write, Description("Cookbook where the file is stored")] string Cookbook;
	[Write, Description("Specify if the file should exist or not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
	[Write, Description("Specify if machine should be rebooted after file has been downloaded or changed")] Boolean Reboot;
	[Write, Description("Path to the cache directory where cookbooks have been downloaded")] string CacheDir;
	[Write, Description("Array containing the services that need to be notified of any change")] string Notifies[];
	[Write, Description("Path to the file that will be used to store the service to restart")] string NotifiesServicePath;
	[Write, Description("Specify that the source is the content to be written out to the file")] Boolean IsContent;
	[Write, Description("The encoding to be used for the file"), ValueMap{"UTF8", "UTF7", "Ascii", "Unicode", "UTF32"}, Values{"UTF8", "UTF7", "Ascii", "Unicode", "UTF32"}] string Encoding;
	[Write, Description("State if byte order mark (BOM) should be enabled")] Boolean WithBOM;
};
